apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.operatorframework.io/operator-type: non-standalone
  name: designate-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DesignateCentrals is the Schema for the designatecentrals API
      displayName: Designate Centrals
      kind: DesignateCentrals
      name: designatecentrals.designate.openstack.org
      version: v1beta1
    - description: DesignateUnbound is the Schema for the designateunbound API
      displayName: Designate Unbound
      kind: DesignateUnbound
      name: designateunbounds.designate.openstack.org
      version: v1beta1
    - description: DesignateAPI is the Schema for the designateapis API
      displayName: Designate API
      kind: DesignateAPI
      name: designateapis.designate.openstack.org
      version: v1beta1
    - description: DesignateCentral is the Schema for the designatecentral API
      displayName: Designate Central
      kind: DesignateCentral
      name: designatecentrals.designate.openstack.org
      version: v1beta1
    - description: DesignateMdns is the Schema for the designatemdnses API
      displayName: Designate Mdns
      kind: DesignateMdns
      name: designatemdnses.designate.openstack.org
      version: v1beta1
    - description: DesignateProducer is the Schema for the designateproducer API
      displayName: Designate Producer
      kind: DesignateProducer
      name: designateproducers.designate.openstack.org
      version: v1beta1
    - description: Designate is the Schema for the designates API
      displayName: Designate
      kind: Designate
      name: designates.designate.openstack.org
      version: v1beta1
    - description: DesignateWorker is the Schema for the designateworker API
      displayName: Designate Worker
      kind: DesignateWorker
      name: designateworkers.designate.openstack.org
      version: v1beta1
  description: Designate Operator
  displayName: Designate Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Network
  - Designate
  links:
  - name: Designate Operator
    url: https://github.com/openstack-k8s-operators/designate-operator
  maturity: alpha
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
